# Generated by Django 3.0.2 on 2020-02-27 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='заголовок напоминания')),
                ('text', models.TextField(verbose_name='текст напоминания')),
                ('pub_date', models.DateTimeField(verbose_name='дата публикации')),
                ('important', models.BooleanField(default=False, verbose_name='важность')),
                ('public', models.BooleanField(default=False, verbose_name='опубликовано или нет')),
                ('url', models.SlugField(max_length=100, unique=True)),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
